baseURL = "https://bilus.dev/"
languageCode = "en-us"
title = "bilus.dev"
theme = "hugo_theme_pickles"
copyright = "&copy; 2020 Marcin Bilski"


[markup.goldmark.renderer]
  unsafe = true

[params]
  paginate = 10
  github = "bilus"
  logo = "/images/logo.png"
  avatar = "/images/author-sm.png"
  bio = "“Learning to see the puzzle in everything. They're everywhere.” -- Holmes<br><br>Though I didn't start my career in 1854, the year Holmes found his life's calling, it's been 24 years since I started writing code for a living."
  contact = "mailto:gyamtso@gmail.com"
  subtitle = "Puzzles I've solved while writing software. A personal blog."
  subtitleShort = "Puzzles I've solved while writing software."
  authorwebsite = "https://bilus.dev"

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
