version: '2'

services:
    remark42:
        image: umputun/remark42:latest
        restart: always
        container_name: "remark42"
        environment:
            - REMARK_URL=https://remark24.bilus.dev  # url pointing to your remark42 server
            - SITE=blog                     # site ID, same as used for `site_id`, see "Setup on your website"
            - SECRET=724827403871620836027           # secret key
            - AUTH_GITHUB_CID=12345667890           # oauth2 client ID
            - AUTH_GITHUB_CSEC=abcdefg12345678      # oauth2 client secret
        volumes:
            - ./var:/srv/var                        # persistent volume to store all remark42 data
